apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tools-ignite
  name: tools-ignite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tools-ignite
  template:
    metadata:
      labels:
        app: tools-ignite
    spec:
      containers:
      - image: registry.aliyuncs.com/opsflow/ops:ignite
        imagePullPolicy: Always
        name: tools-ignite
        ports:
        - containerPort: 80
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
