name: Docker Image CI

on:
  workflow_dispatch:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
#   schedule:
#     - cron: 15 1 * * *

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag xlovepython/tools:$(date +%s)
      
    - name: login docker hub
      run: docker login -u xlovepython -p ${{ secrets.credential }}
      
    - name: Push the Docker image
      run: docker push  xlovepython/tools:$(date +%s)
      
